import { TwitterModuleState } from "@/modules/twitter/state/twitter-types";

export const initialTwitterState: TwitterModuleState = {
  theme: "dim",
  view: "tweet",
  primaryTweet: {
    id: "tweet-1",
    name: "Fake Web",
    username: "fakewebapp",
    avatarAssetId: null,
    content:
      "The X/Twitter module now supports tweet rendering, thread layouts, and status screens.",
    mediaAssetId: null,
    mediaAlt: "",
    timestamp: "2026-05-16T20:42:00.000Z",
    views: "12.4K",
    comments: "164",
    retweets: "482",
    likes: "4.9K",
    bookmarks: "217",
    showTimestamp: true,
    showMetrics: false,
  },
  replyChain: [
    {
      id: "reply-1",
      name: "Ava Design",
      username: "avadsgn",
      avatarAssetId: null,
      content: "Make the tweet shell feel native and keep the export output crisp.",
      mediaAssetId: null,
      mediaAlt: "",
      timestamp: "2026-05-16T20:49:00.000Z",
      views: "2,013",
      comments: "22",
      retweets: "91",
      likes: "1.2K",
      bookmarks: "38",
      showTimestamp: true,
      showMetrics: false,
    },
    {
      id: "reply-2",
      name: "Milo",
      username: "milotype",
      avatarAssetId: null,
      content:
        "The theme switch needs the exact Light, Dim, and Dark backgrounds.",
      mediaAssetId: null,
      mediaAlt: "",
      timestamp: "2026-05-16T21:03:00.000Z",
      views: "967",
      comments: "11",
      retweets: "45",
      likes: "802",
      bookmarks: "19",
      showTimestamp: true,
      showMetrics: false,
    },
  ],
};
